# 📁 project_config.yaml

project:
  name: inat-habitat-modeling
  owner: Jakob Koeppen
  description: Modellierung von Habitatpräferenzen auf Basis von iNaturalist- und Remote-Sensing-Daten

gee:
  default_project: inaturalist-474012
  drive_folder_ndvi: iNaturalist/NDVI_Exports
  drive_folder_ndwi: iNaturalist/NDWI_Exports
  region_default:
    name: BerlinBB
    bounds: [12.8, 52.2, 13.8, 52.8]  # lon_min, lat_min, lon_max, lat_max

inat:
  default_taxon_id: 48620  # Chicken of the Woods
  max_accuracy: 30
  bbox_default: [12.8, 52.2, 13.8, 52.8]

features:
  ndvi:
    source: NDVI_Exports
    variables: [NDVI_at_point, NDVI_std_100m]
  ndwi:
    source: NDWI_Exports
    variables: [NDWI_at_point, NDWI_std_100m]

export:
  start_year: 2021
  end_year: 2025
  months: [5, 6, 7, 8, 9]
  scale: 10
  max_pixels: 1e13